name: CD
on:
  push:
    tags:
      - "v*"

jobs:
  deploy-sonatype:
    name: Deploy to Sonatype
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup GPG
        uses: olafurpg/setup-gpg@v2
      - name: Deploy to Sonatype
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  deploy-npm:
    name: Deploy to NPM Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare JS package
        run: |
          sbt fullOptJS
          cp js/src/main/resources/* jspackage
          cp js/target/scala-2.13/engine-opt.js jspackage/engine.js
          sed 's/$VERSION/'"${REF##*/v}/" < jspackage/package.json.in > jspackage/package.json
        env:
          REF: ${{ github.ref }}
      - name: Deploy to NPM Registry
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: jspackage
