name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  scala:
    name: Check Scala style conventions and run Scala tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Test style conventions
        run: sbt scalafmtCheckAll
      - name: Run Scala tests
        run: sbt test
  javascript:
    name: Run JS tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Prepare JS package
        run: |
          sbt fullOptJS
          cp js/src/main/resources/* jspackage
          cp js/target/scala-2.13/engine-opt.js jspackage/engine.js
          sed 's/$VERSION/0.1.0-SNAPSHOT/' < jspackage/package.json.in > jspackage/package.json
        env:
          REF: ${{ github.ref }}
      - name: Run JavaScript tests
        run: |
          npm install
          npm test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: jspackage
